"use client";

import { Montserrat } from "next/font/google";
import "@rainbow-me/rainbowkit/styles.css";
import { getDefaultWallets, RainbowKitProvider } from "@rainbow-me/rainbowkit";
import { configureChains, createConfig, WagmiConfig } from "wagmi";
import { sepolia, avalancheFuji } from "wagmi/chains";
import { alchemyProvider } from "wagmi/providers/alchemy";
import { publicProvider } from "wagmi/providers/public";
import "./globals.css";
import dynamic from "next/dynamic";
const ConnectWalletModal = dynamic(
  () => import("./components/ConnectWalletModal"),
  { ssr: false }
);
const MenuBar = dynamic(() => import("./components/MenuBar"), { ssr: false });

const montserrat = Montserrat({ subsets: ["latin"] });

/*Configure Rainbow Kit*/
const { chains, publicClient } = configureChains(
  [sepolia, avalancheFuji],
  [alchemyProvider({ apiKey: "QGCJ46bYN5eef_-YWFqOMROVbfIO3WcI" }), publicProvider()]
);

const { connectors } = getDefaultWallets({
  appName: "PromptFighters",
  projectId: "PFT",
  chains,
});

const wagmiConfig = createConfig({
  autoConnect: true,
  connectors,
  publicClient,
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <WagmiConfig config={wagmiConfig}>
          <RainbowKitProvider chains={chains}>
            <div className=" flex flex-col w-screen h-screen relative bg-pf-light-blue">
              <ConnectWalletModal />
              <nav className="relative select-none bg-grey lg:flex lg:items-stretch w-full p-3">
                <MenuBar />
              </nav>
              {children}
            </div>
          </RainbowKitProvider>
        </WagmiConfig>
      </body>
    </html>
  );
}
